In [21]:
import numpy as np

In [22]:
M = np.array([[0, 0.5, 1/3, 0], [0.5, 0, 1/3, 0], [1/2, 1/2, 0, 1], [0, 0, 1/3, 0]])
r = np.array([0,0,1,0])

In [23]:
M

array([[0.        , 0.5       , 0.33333333, 0.        ],
       [0.5       , 0.        , 0.33333333, 0.        ],
       [0.5       , 0.5       , 0.        , 1.        ],
       [0.        , 0.        , 0.33333333, 0.        ]])

In [24]:
r

array([0, 0, 1, 0])

In [25]:
np.matmul(M, r)

array([0.33333333, 0.33333333, 0.        , 0.33333333])

In [26]:
for i in range(100):
    r = np.matmul(M,r)
    print(f"Iteration {(i+1)}, {r}")

Iteration 1, [0.33333333 0.33333333 0.         0.33333333]
Iteration 2, [0.16666667 0.16666667 0.66666667 0.        ]
Iteration 3, [0.30555556 0.30555556 0.16666667 0.22222222]
Iteration 4, [0.20833333 0.20833333 0.52777778 0.05555556]
Iteration 5, [0.28009259 0.28009259 0.26388889 0.17592593]
Iteration 6, [0.22800926 0.22800926 0.45601852 0.08796296]
Iteration 7, [0.2660108  0.2660108  0.31597222 0.15200617]
Iteration 8, [0.23832948 0.23832948 0.41801698 0.10532407]
Iteration 9, [0.25850373 0.25850373 0.34365355 0.13933899]
Iteration 10, [0.24380305 0.24380305 0.39784272 0.11455118]
Iteration 11, [0.25451576 0.25451576 0.35835423 0.13261424]
Iteration 12, [0.24670929 0.24670929 0.38713    0.11945141]
Iteration 13, [0.25239798 0.25239798 0.3661607  0.12904333]
Iteration 14, [0.24825256 0.24825256 0.38144132 0.12205357]
Iteration 15, [0.25127338 0.25127338 0.37030613 0.12714711]
Iteration 16, [0.24907207 0.24907207 0.37842049 0.12343538]
Iteration 17, [0.2506762  0.2506762  0.37250744 0